apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTURNeApPRFExTURGYUZ3MDBNakEyTURNeE9EUTFNREZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERGZzNXNjZkdjRHpjYkI4L2VpRXMvN1dYb2VjVC9ReE8rcGZrVFd6cE94NStlS1k4NwpaK1Q4bFBscU1yenVKRG9MTGFCcTRjcW9nSXBYNDdOUkJOM0s5R2NreXZ3dXprTGhSWlgrU01MT3Y2aXFsN1dZCktUZmxxYUFTam5wMGxCSkZPVTZhS2hXZkdJckNHb2FpbDU4TjcrRlk2Mk1kOFJMY2JVZGZiajk5eWdScm8yNXUKRmdBN1VnckdRd0FKYmVDRU1yNEhJdURTM0VtenFXV3A3OVoySmhub05yWmxLMTFnbE9TNGxVVzgzZkthT2J6WAp3ZENCUDd0dzMwRnpYb3ZmYVJSN0pmNngrVEE1dGxnVnNxZ2QxKzVnQ2lvUTlKK1J3OGlXR1NTd3BDa1NEcm4yCkk5Vnh5V3VwUXM0VzlYSkpIcVF5MFhSeEdyTnM2Q3YyYVhaZEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRoeFJodThTL1hIcExtS1FQUAo3dWtKWGJpVFR6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF1SjhudWhhWXZtaWxEQW13eDhRZjRoeEZFL050CklXZi9CYlF0NHVQUnRkNFQxRlBleEU4aGgrYmtNcGtlVFZUL05Ec2ovb3lFbFd2bEpseG9KckF5S3VNaGppZW0KdExhN2FDRStsZXpuL2lsYmRudXRMUkdUaXUzTm1xTWo0SG9qbHJRS0pkUGFoRVhNc1YzQ1JsQVJySXROcmJVSQpwamNEVFdsVGtsY2cxbUNoTllTUXRFamw4eTd4UGRMd20ydGFKRnEza1E4NGRGMFpRdHBwbCtLdGdwcGdHbTRNCmduVXEvK1ZGbWFDQ04ySlZyd250WlJJM0pidFhraUpRcXB6aUkxM2FQNkdBUmNmcHVVOFp3bjkrdXlhQ2pYQ2wKQzNqUzNCWHc1OWxta1NQeGhQTWlmYStYYW1lVjEwbHB6bll3eHZrSmtNQnYxWVBpYi9GR0JkbFRNQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://54564ce6-1415-4479-936e-cb7e91831179.k8s.ondigitalocean.com
  name: do-sfo3-udemy-microservices-nodejs
contexts:
- context:
    cluster: do-sfo3-udemy-microservices-nodejs
    user: do-sfo3-udemy-microservices-nodejs-admin
  name: do-sfo3-udemy-microservices-nodejs
current-context: do-sfo3-udemy-microservices-nodejs
kind: Config
preferences: {}
users:
- name: do-sfo3-udemy-microservices-nodejs-admin
  user:
    token: dop_v1_f8853b1720ba22a267865425c10eb6ad14466772d56187273716a7dd831b3d6a
