name: deploy-tickets

on: 
  push:
    branches:
      - master
    paths:
      - 'ticketing/tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/tickets && docker build -t igordonin/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push igordonin/tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save udemy-microservices-nodejs
      - run: kubectl rollout restart deployment tickets-depl