name: deploy-manifests

on: 
  push:
    branches:
      - master
    paths:
      - 'ticketing/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save udemy-microservices-nodejs
      - run: kubectl apply -f ticketing/infra/k8s && kubectl apply -f ticketing/infra/k8s-prod