name: tests-orders

on: 
  pull_request:
    paths:
      - 'ticketing/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/orders && npm i && npm run test:ci
