name: tests-auth

on: 
  pull_request:
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/auth && npm i && npm run test:ci
