name: tests-payments

on: 
  pull_request:
    paths:
      - 'ticketing/payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/payments && npm i && npm run test:ci
